apiVersion: v1
kind: Service
metadata:
  name: broker-3
  namespace: kafka
spec:
  selector:
    app: broker-3
  ports:
    - port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-3
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-3
  template:
    metadata:
      labels:
        app: broker-3
    spec:
      nodeSelector:
        kubernetes.io/hostname: "ip-172-31-31-160"
      containers:
        - name: broker
          image: apache/kafka:4.1.1
          ports:
            - containerPort: 9092
              hostPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: "6"
            - name: KAFKA_PROCESS_ROLES
              value: "broker"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-3:19092,PLAINTEXT_HOST://broker-3:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: data
          hostPath:
            path: /data/kafka/broker-3
            type: DirectoryOrCreate