---
- name: Deploy RKE2 Cluster (3 Masters, 3 Workers)
  hosts: all
  become: yes
  gather_facts: no

  vars:
    rke2_version: "v1.34.1+rke2r1"
    rke2_server_config_dir: "/etc/rancher/rke2"
    rke2_server_config: "/etc/rancher/rke2/config.yaml"
    rke2_agent_config: "/etc/rancher/rke2/config.yaml"
    rke2_token_file: "/var/lib/rancher/rke2/server/token"

  tasks:
    ###########################################################################
    # 0. ENSURE PYTHON EXISTS (BECAUSE gather_facts IS DISABLED)
    ###########################################################################
    - name: Ensure Python is installed
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
            apt-get update -y && apt-get install -y python3
        fi
      changed_when: false

    ###########################################################################
    # 1. CHECK IF RKE2 IS INSTALLED
    ###########################################################################
    - name: Check if RKE2 server binary exists
      stat:
        path: /usr/local/bin/rke2-server
      register: rke2_server_bin
      when: "'masters' in group_names"

    - name: Check if RKE2 agent binary exists
      stat:
        path: /usr/local/bin/rke2-agent
      register: rke2_agent_bin
      when: "'workers' in group_names"

    ###########################################################################
    # 2. DOWNLOAD INSTALL SCRIPT IF MISSING
    ###########################################################################
    - name: Download RKE2 install script
      get_url:
        url: https://get.rke2.io
        dest: /tmp/rke2-install.sh
        mode: '0755'
      when: >
        ('masters' in group_names and not rke2_server_bin.stat.exists) or
        ('workers' in group_names and not rke2_agent_bin.stat.exists)

    ###########################################################################
    # 3. INSTALL RKE2 SERVER OR AGENT
    ###########################################################################
    - name: Install RKE2 server
      command: "sh /tmp/rke2-install.sh"
      environment:
        INSTALL_RKE2_VERSION: "{{ rke2_version }}"
      register: install_rke2_server
      when: "'masters' in group_names and not rke2_server_bin.stat.exists"

    - name: Install RKE2 agent
      command: "sh /tmp/rke2-install.sh"
      environment:
        INSTALL_RKE2_VERSION: "{{ rke2_version }}"
      register: install_rke2_agent
      when: "'workers' in group_names and not rke2_agent_bin.stat.exists"

    - debug:
        var: install_rke2_agent
      when: "'workers' in group_names and not rke2_agent_bin.stat.exists"

    ###########################################################################
    # 4. CONFIGURE MASTER NODES
    ###########################################################################
    - name: Create RKE2 server config dir
      file:
        path: "{{ rke2_server_config_dir }}"
        state: directory
        mode: '0755'
      when: "'masters' in group_names"

    - name: Generate RKE2 server config
      copy:
        dest: "{{ rke2_server_config }}"
        content: |
          token: "{{ hostvars[groups['masters'][0]].cluster_token }}"
          tls-san:
            - "{{ groups['masters'][0] }}"
          node-name: "{{ inventory_hostname }}"
          cluster-cidr: "10.42.0.0/16"
          service-cidr: "10.43.0.0/16"
          write-kubeconfig-mode: "0644"
      when: "'masters' in group_names"

    ###########################################################################
    # 5. IF FIRST MASTER: CREATE TOKEN
    ###########################################################################
    - name: Check if cluster token file exists
      stat:
        path: "{{ rke2_token_file }}"
      register: token_file_stat
      when: inventory_hostname == groups['masters'][0]

    - name: Create cluster token (first master only)
      command: "rke2 token generate"
      register: token_output
      when: inventory_hostname == groups['masters'][0] and not token_file_stat.stat.exists

    - name: Save cluster token to file
      copy:
        dest: "{{ rke2_token_file }}"
        mode: '0600'
        content: "{{ token_output.stdout }}"
      when: inventory_hostname == groups['masters'][0] and not token_file_stat.stat.exists

    - name: Load cluster token
      slurp:
        src: "{{ rke2_token_file }}"
      register: slurped_token
      when: inventory_hostname == groups['masters'][0]

    - name: Share token
      set_fact:
        cluster_token: "{{ slurped_token.content | b64decode | trim }}"
      when: inventory_hostname == groups['masters'][0]

    ###########################################################################
    # 6. START MASTER SERVICES
    ###########################################################################
    - name: Enable / start rke2-server
      systemd:
        name: rke2-server
        state: started
        enabled: yes
      when: "'masters' in group_names"

    ###########################################################################
    # 7. CONFIGURE WORKER NODES
    ###########################################################################
    - name: Create RKE2 agent config dir
      file:
        path: "{{ rke2_server_config_dir }}"
        state: directory
        mode: '0755'
      when: "'workers' in group_names"

    - name: Generate RKE2 agent config
      copy:
        dest: "{{ rke2_agent_config }}"
        content: |
          server: "https://{{ hostvars[groups['masters'][0]].ansible_host }}:9345"
          token: "{{ hostvars[groups['masters'][0]].cluster_token }}"
          node-name: "{{ inventory_hostname }}"
      when: "'workers' in group_names"

    ###########################################################################
    # 8. START WORKER SERVICE
    ###########################################################################
    - name: Enable / start rke2-agent
      systemd:
        name: rke2-agent
        state: started
        enabled: yes
      when: "'workers' in group_names"

    ###########################################################################
    # 9. DEBUG OUTPUT
    ###########################################################################
    - name: Debug installed binaries
      debug:
        msg: |
          SERVER BINARY EXISTS: {{ rke2_server_bin.stat.exists | default('N/A') }}
          AGENT BINARY EXISTS: {{ rke2_agent_bin.stat.exists | default('N/A') }}
