- name: Deploy RKE2 Cluster (3 masters + 3 workers)
  hosts: k8s_cluster
  become: yes
  gather_facts: no

  vars:
    rke2_version: "v1.34.1+rke2r1"
    rke2_server_config_path: "/etc/rancher/rke2/config.yaml"
    rke2_agent_config_path: "/etc/rancher/rke2/config.yaml"
    master0: "{{ groups['masters'][0] }}"

  tasks:
    # --------------------------------------------------------------------------
    # 0. Bootstrap Python if missing
    # --------------------------------------------------------------------------
    - name: Bootstrap Python if missing
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          apt-get update && apt-get install -y python3 python3-apt
        fi
      changed_when: false

    - name: Wait after Python setup
      raw: sleep 2
      changed_when: false

    - name: Gather facts now that python exists
      setup:

    # --------------------------------------------------------------------------
    # 1. Install system dependencies
    # --------------------------------------------------------------------------
    - name: Install dependencies
      apt:
        name:
          - curl
          - wget
          - python3
          - python3-pip
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: yes

    # --------------------------------------------------------------------------
    # Create /etc/rancher/rke2 directory on all hosts
    # --------------------------------------------------------------------------
    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: "0755"

    # --------------------------------------------------------------------------
    # 2. Install RKE2
    # --------------------------------------------------------------------------
    - name: Check if RKE2 is installed
      stat:
        path: /usr/local/bin/rke2
      register: rke2_installed

    - name: Download RKE2 installer
      get_url:
        url: https://get.rke2.io
        dest: /tmp/rke2-install.sh
        mode: "0755"
      when: not rke2_installed.stat.exists

    - name: Install RKE2
      command: "sh /tmp/rke2-install.sh"
      environment:
        INSTALL_RKE2_VERSION: "{{ rke2_version }}"
      when: not rke2_installed.stat.exists
      register: rke2_install_output

    - debug:
        var: rke2_install_output
      when: not rke2_installed.stat.exists

    # --------------------------------------------------------------------------
    # 3. Prepare MASTER0 configuration
    # --------------------------------------------------------------------------
    - name: Generate RKE2 master0 server config
      copy:
        dest: "{{ rke2_server_config_path }}"
        mode: "0600"
        content: |
          token: "server-bootstrap"
          node-name: "{{ inventory_hostname }}"
          tls-san:
            - "{{ ansible_host }}"
          write-kubeconfig-mode: "0644"
      when: inventory_hostname == master0

    - name: Enable and start rke2-server on master0
      systemd:
        name: rke2-server
        state: started
        enabled: yes
      when: inventory_hostname == master0

    - name: Wait for token file to appear (master0)
      wait_for:
        path: /var/lib/rancher/rke2/server/token
        state: present
        timeout: 120
      when: inventory_hostname == master0

    - name: Read master0 real token
      slurp:
        src: /var/lib/rancher/rke2/server/token
      register: raw_token
      when: inventory_hostname == master0

    - name: Decode token
      set_fact:
        cluster_token: "{{ raw_token.content | b64decode | trim }}"
      when: inventory_hostname == master0

    - debug:
        var: cluster_token
      when: inventory_hostname == master0

    # --------------------------------------------------------------------------
    # 4. Share token with all nodes (wait until cluster_token is available)
    # --------------------------------------------------------------------------
    - name: Wait for master0 token to be available
      wait_for:
        timeout: 120
      when: inventory_hostname != master0 and (hostvars[master0].cluster_token is not defined or hostvars[master0].cluster_token == '')

    - name: Share token to all hosts
      set_fact:
        shared_token: "{{ hostvars[master0].cluster_token }}"
      when: hostvars[master0].cluster_token is defined

    - debug:
        msg: "Node {{ inventory_hostname }} received token {{ shared_token }}"
      when: shared_token is defined

    # --------------------------------------------------------------------------
    # 5. Configure remaining masters
    # --------------------------------------------------------------------------
    - name: Generate RKE2 server config for other masters
      copy:
        dest: "{{ rke2_server_config_path }}"
        mode: "0600"
        content: |
          token: "{{ shared_token }}"
          server: https://{{ hostvars[master0].ansible_host }}:9345
          node-name: "{{ inventory_hostname }}"
          tls-san:
            - "{{ ansible_host }}"
          write-kubeconfig-mode: "0644"
      when: inventory_hostname in groups['masters'] and inventory_hostname != master0

    - name: Enable & start rke2-server (other masters)
      systemd:
        name: rke2-server
        state: started
        enabled: yes
      when: inventory_hostname in groups['masters'] and inventory_hostname != master0

    # --------------------------------------------------------------------------
    # 6. Configure workers
    # --------------------------------------------------------------------------
    - name: Generate RKE2 agent config
      copy:
        dest: "{{ rke2_agent_config_path }}"
        mode: "0600"
        content: |
          server: https://{{ hostvars[master0].ansible_host }}:9345
          token: "{{ shared_token }}"
          node-name: "{{ inventory_hostname }}"
      when: inventory_hostname in groups['workers']

    - name: Enable & start rke2-agent
      systemd:
        name: rke2-agent
        state: started
        enabled: yes
      when: inventory_hostname in groups['workers']

    # --------------------------------------------------------------------------
    # 7. Final cluster verification (master0)
    # --------------------------------------------------------------------------
    - name: Verify cluster
      shell: /var/lib/rancher/rke2/bin/kubectl get nodes -o wide
      register: cluster_nodes
      when: inventory_hostname == master0

    - debug:
        var: cluster_nodes.stdout
      when: inventory_hostname == master0
