- name: Deploy RKE2 Cluster (3 Masters + 3 Workers)
  hosts: k8s_cluster
  become: yes
  gather_facts: no        # Python may not exist yet; disable default facts

  vars:
    rke2_version: "v1.34.1+rke2r1"
    rke2_server_config: "/etc/rancher/rke2/config.yaml"
    rke2_agent_config: "/etc/rancher/rke2/config.yaml"
    master0: "{{ groups['masters'][0] }}"

  handlers:
    - name: reload sysctl
      shell: sysctl --system

    - name: reload modules
      shell: modprobe br_netfilter && modprobe overlay

  tasks:
    # --------------------------------------------------------------------
    # PHASE 0 — BOOTSTRAP PYTHON (raw mode, idempotent)
    # --------------------------------------------------------------------
    - name: Bootstrap Python3 (raw, runs even without Python)
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          apt-get update && apt-get install -y python3 python3-apt
        fi
      changed_when: false
      tags: bootstrap

    - name: Wait after Python installation
      raw: sleep 2
      changed_when: false
      tags: bootstrap

    - name: Gather Ansible facts AFTER Python exists
      setup:
      tags: bootstrap

    # --------------------------------------------------------------------
    # PHASE 1 — PREPARE NODES
    # --------------------------------------------------------------------
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: prepare

    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - ca-certificates
          - apt-transport-https
          - curl
          - wget
          - tar
          - snapd
        state: present
      tags: prepare

    # --------------------------------------------------------------------
    # COMMON SYSTEM SETUP
    # --------------------------------------------------------------------
    - name: Enable kernel modules for Kubernetes
      copy:
        dest: /etc/modules-load.d/rke2.conf
        content: |
          br_netfilter
          overlay
      notify: reload modules

    - name: Configure sysctl requirements for Kubernetes
      copy:
        dest: /etc/sysctl.d/90-rke2.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      notify: reload sysctl

    # --------------------------------------------------------------------
    # INSTALL RKE2 (idempotent)
    # --------------------------------------------------------------------
    - name: Check if RKE2 is already installed
      stat:
        path: /usr/local/bin/rke2
      register: rke2_installed

    - name: Download RKE2 installer script
      get_url:
        url: https://get.rke2.io
        dest: /tmp/rke2-install.sh
        mode: '0755'
      when: not rke2_installed.stat.exists

    - name: Install RKE2
      shell: INSTALL_RKE2_VERSION={{ rke2_version }} sh /tmp/rke2-install.sh
      when: not rke2_installed.stat.exists
      register: rke2_install_result

    - debug:
        var: rke2_install_result
      when: not rke2_installed.stat.exists

    # --------------------------------------------------------------------
    # MASTER 0 — GENERATE/THE TOKEN
    # --------------------------------------------------------------------
    - name: Ensure token exists on master0
      stat:
        path: /var/lib/rancher/rke2/server/token
      register: token_file
      when: inventory_hostname == master0

    - debug:
        var: token_file
      when: inventory_hostname == master0

    - name: Read cluster token
      set_fact:
        cluster_token: "{{ lookup('file', '/var/lib/rancher/rke2/server/token') }}"
      when: inventory_hostname == master0 and token_file.stat.exists

    - debug:
        var: cluster_token
      when: inventory_hostname == master0

    # --------------------------------------------------------------------
    # STEP: PROPAGATE TOKEN TO ALL NODES
    # --------------------------------------------------------------------
    - name: Share token to all hosts
      add_host:
        name: "{{ item }}"
        cluster_token: "{{ hostvars[master0].cluster_token }}"
      loop: "{{ groups['k8s_cluster'] }}"
      when: inventory_hostname == master0

    # --------------------------------------------------------------------
    # MASTER CONFIGURATION
    # --------------------------------------------------------------------
    - name: Create RKE2 server config
      copy:
        dest: "{{ rke2_server_config }}"
        mode: '0600'
        content: |
          token: "{{ hostvars[master0].cluster_token }}"
          node-name: "{{ inventory_hostname }}"
          tls-san:
            - "{{ hostvars[inventory_hostname].ansible_host }}"
          disable:
            - rke2-ingress-nginx
          write-kubeconfig-mode: "0644"
      when: inventory_hostname in groups['masters']

    - name: Enable and start rke2-server
      systemd:
        name: rke2-server
        enabled: yes
        state: started
      when: inventory_hostname in groups['masters']

    - name: Wait until master API server is responding
      shell: /var/lib/rancher/rke2/bin/kubectl get nodes
      register: kubectl_check
      retries: 20
      delay: 10
      failed_when: false
      when: inventory_hostname in groups['masters']

    - debug:
        var: kubectl_check
      when: inventory_hostname in groups['masters']

    # --------------------------------------------------------------------
    # WORKERS
    # --------------------------------------------------------------------
    - name: Create RKE2 agent config
      copy:
        dest: "{{ rke2_agent_config }}"
        mode: '0600'
        content: |
          server: https://{{ hostvars[master0].ansible_host }}:9345
          token: "{{ hostvars[master0].cluster_token }}"
          node-name: "{{ inventory_hostname }}"
      when: inventory_hostname in groups['workers']

    - name: Enable + start rke2-agent
      systemd:
        name: rke2-agent
        enabled: yes
        state: started
      when: inventory_hostname in groups['workers']

    - name: Tail agent logs (for debugging)
      shell: journalctl -u rke2-agent -n 20 --no-pager
      register: agent_logs
      when: inventory_hostname in groups['workers']

    - debug:
        var: agent_logs
      when: inventory_hostname in groups['workers']

    # --------------------------------------------------------------------
    # FINAL VERIFY — MASTER0 only
    # --------------------------------------------------------------------
    - name: Get cluster nodes
      shell: /var/lib/rancher/rke2/bin/kubectl get nodes -o wide
      register: cluster_nodes
      when: inventory_hostname == master0

    - debug:
        msg: "{{ cluster_nodes.stdout }}"
      when: inventory_hostname == master0
