---
- name: Enable memory cgroups and reboot nodes
  hosts: k8s_cluster
  become: yes
  gather_facts: no
  serial: 1

  vars:
    grub_file: /etc/default/grub
    grub_flags: "systemd.unified_cgroup_hierarchy=1 cgroup_enable=memory swapaccount=1"
    primary_master: "{{ groups['masters'][0] }}"
    rke2_kubeconfig: /etc/rancher/rke2/rke2.yaml

  tasks:

    - name: Ensure python3 installed
      raw: |
        if ! command -v python3 >/dev/null 2>&1 ; then
          apt update -y && apt install -y python3
        fi
      changed_when: false

    - name: Gather facts
      setup:

    - name: Show current cmdline
      command: cat /proc/cmdline
      register: cmdline

    - debug:
        var: cmdline.stdout

    - name: Ensure br_netfilter modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    - name: Ensure sysctl for kubernetes
      copy:
        dest: /etc/sysctl.d/99-k8s.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Insert GRUB flags
      lineinfile:
        path: "{{ grub_file }}"
        regexp: '^GRUB_CMDLINE_LINUX='
        line: "GRUB_CMDLINE_LINUX=\"{{ grub_flags }}\""
      register: grubedit

    - debug:
        var: grubedit

    - name: Update grub if changed
      command: update-grub
      when: grubedit.changed

    - name: Reboot if grub updated
      reboot:
        reboot_timeout: 600
      when: grubedit.changed

    - name: Check memory cgroup after reboot
      shell: |
        if [ -f /sys/fs/cgroup/memory.max ] || [ -d /sys/fs/cgroup/memory ]; then
          echo ok
        else
          echo missing
        fi
      register: cgcheck

    - debug:
        var: cgcheck.stdout

    - name: Fail if memory cgroup still missing
      fail:
        msg: "Memory cgroup STILL missing!"
      when: cgcheck.stdout != "ok"

    - name: Restart rke2
      systemd:
        name: "{{ 'rke2-server' if inventory_hostname in groups['masters'] else 'rke2-agent' }}"
        state: restarted
        enabled: yes

    - name: Wait for api (masters only)
      when: inventory_hostname == primary_master
      shell: "kubectl --kubeconfig={{ rke2_kubeconfig }} get nodes"
      register: kcheck
      retries: 20
      delay: 10
      until: kcheck.rc == 0
      failed_when: false

    - debug:
        var: kcheck.stdout
      when: inventory_hostname == primary_master
