- name: Deploy MicroK8s Cluster on Debian
  hosts: k8s_cluster
  become: yes
  gather_facts: yes
  
  vars:
    microk8s_channel: "latest/stable"
    microk8s_plugins:
      - dns
      - storage
      - ingress
    primary_master: "{{ groups['masters'][0] }}"
  
  tasks:
    # Phase 1: Prepare all nodes
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: prepare

    - name: Install Python3 and dependencies
      apt:
        name:
          - python3
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - snapd
        state: present
      tags: prepare

    - name: Ensure snapd service is running
      systemd:
        name: snapd
        state: started
        enabled: yes
      tags: prepare

    - name: Wait for snapd to be ready
      command: snap wait system seed.loaded
      changed_when: false
      tags: prepare

    # Phase 2: Install MicroK8s on all nodes
    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        channel: "{{ microk8s_channel }}"
      tags: install

    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes
      tags: install

    - name: Create .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      tags: install

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      changed_when: false
      retries: 10
      delay: 10
      tags: install

    # Phase 3: Configure primary master
    - name: Enable MicroK8s addons on primary master
      command: "microk8s enable {{ item }}"
      loop: "{{ microk8s_plugins }}"
      when: inventory_hostname == primary_master
      register: enable_addons
      changed_when: "'Enabling' in enable_addons.stdout"
      tags: configure

    - name: Enable HA clustering on primary master
      command: microk8s enable ha-cluster
      when: inventory_hostname == primary_master
      register: ha_enable
      changed_when: "'Enabling' in ha_enable.stdout"
      tags: configure

    - name: Wait for primary master to be ready
      command: microk8s status --wait-ready
      when: inventory_hostname == primary_master
      changed_when: false
      tags: configure

    # Phase 4: Generate join tokens
    - name: Generate join token for additional masters
      command: microk8s add-node --token-ttl -1
      when: inventory_hostname == primary_master
      register: master_join_command
      changed_when: false
      tags: cluster

    - name: Extract master join command
      set_fact:
        master_join_token: "{{ master_join_command.stdout_lines | select('match', '.*microk8s join.*') | first }}"
      when: inventory_hostname == primary_master
      tags: cluster

    - name: Generate join token for workers
      command: microk8s add-node --token-ttl -1 --worker
      when: inventory_hostname == primary_master
      register: worker_join_command
      changed_when: false
      tags: cluster

    - name: Extract worker join command
      set_fact:
        worker_join_token: "{{ worker_join_command.stdout_lines | select('match', '.*microk8s join.*') | first }}"
      when: inventory_hostname == primary_master
      tags: cluster

    # Phase 5: Join additional masters
    - name: Store master join token
      set_fact:
        master_token: "{{ hostvars[primary_master]['master_join_token'] }}"
      when: 
        - inventory_hostname in groups['masters']
        - inventory_hostname != primary_master
      tags: cluster

    - name: Join additional master nodes to cluster
      command: "{{ master_token }}"
      when: 
        - inventory_hostname in groups['masters']
        - inventory_hostname != primary_master
      register: master_join_result
      changed_when: "'Successfully joined' in master_join_result.stdout or master_join_result.rc == 0"
      failed_when: false
      tags: cluster

    - name: Wait for additional masters to be ready
      command: microk8s status --wait-ready
      when: 
        - inventory_hostname in groups['masters']
        - inventory_hostname != primary_master
      changed_when: false
      tags: cluster

    # Phase 6: Join worker nodes
    - name: Store worker join token
      set_fact:
        worker_token: "{{ hostvars[primary_master]['worker_join_token'] }}"
      when: inventory_hostname in groups['workers']
      tags: cluster

    - name: Join worker nodes to cluster
      command: "{{ worker_token }}"
      when: inventory_hostname in groups['workers']
      register: worker_join_result
      changed_when: "'Successfully joined' in worker_join_result.stdout or worker_join_result.rc == 0"
      failed_when: false
      tags: cluster

    - name: Wait for worker nodes to be ready
      command: microk8s status --wait-ready
      when: inventory_hostname in groups['workers']
      changed_when: false
      tags: cluster

    # Phase 7: Configure kubectl access
    - name: Generate kubeconfig on primary master
      shell: microk8s config > /home/{{ ansible_user }}/.kube/config
      when: inventory_hostname == primary_master
      tags: config

    - name: Set kubeconfig permissions
      file:
        path: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      when: inventory_hostname == primary_master
      tags: config

    - name: Create kubectl alias
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "alias kubectl='microk8s kubectl'"
        create: yes
      tags: config

    # Phase 8: Verify cluster
    - name: Get cluster nodes
      command: microk8s kubectl get nodes
      when: inventory_hostname == primary_master
      register: cluster_nodes
      changed_when: false
      tags: verify

    - name: Display cluster status
      debug:
        var: cluster_nodes.stdout_lines
      when: inventory_hostname == primary_master
      tags: verify
      