---
- name: Deploy Redpanda Cluster (5 Nodes) with SCRAM
  hosts: redpanda_nodes
  become: yes
  gather_facts: no # Disable initial fact gathering

  # Variables for SCRAM user creation (defined in hosts.ini)
  # rp_superuser=admin
  # rp_password=SuperSecretPassword123!
  
  tasks:
    
    # ====================================================================
    # Phase 0: Bootstrap Python and gather facts (User's requested format)
    # ====================================================================

    - name: Install Python3 and dependencies (raw command, no Python required)
      # WARNING: This 'raw' command is specific to Debian/Ubuntu targets.
      raw: |
        apt-get update
        apt-get install -y python3 python3-apt
      changed_when: false
      when: ansible_os_family is not defined or ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
      tags: bootstrap

    - name: Wait for system to settle
      raw: sleep 2
      changed_when: false
      when: ansible_os_family is not defined or ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
      tags: bootstrap

    - name: Gather facts after Python installation
      setup:
      tags: bootstrap

    # ====================================================================
    # Phase 1: Prepare System & Install Redpanda
    # ====================================================================

    - name: Install required packages (curl, ca-certs)
      package:
        name:
          - curl
          - ca-certificates
        state: present
      tags: prepare

    - name: Setup Redpanda Repo (Debian/Ubuntu)
      shell: curl -1sLf 'https://dl.redpanda.com/nzc4ZYqk3WRGdECz/redpanda/cfg/setup/bash.deb.sh' | bash
      args:
        creates: /etc/apt/sources.list.d/redpanda.list
      when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

    - name: Setup Redpanda Repo (RHEL/CentOS)
      shell: curl -1sLf 'https://dl.redpanda.com/nzc4ZYqk3WRGdECz/redpanda/cfg/setup/bash.rpm.sh' | bash
      args:
        creates: /etc/yum.repos.d/redpanda.repo
      when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS" or ansible_os_family == "Rocky" or ansible_os_family == "AlmaLinux"

    - name: Install Redpanda
      package:
        name: redpanda
        state: latest

    # --- 2. CONFIGURATION & SERVICE START ---
    - name: Deploy Redpanda Config with SASL
      template:
        src: templates/redpanda.yaml.j2
        dest: /etc/redpanda/redpanda.yaml
        owner: redpanda
        group: redpanda
        mode: '0644'
      notify: Restart Redpanda

    - name: Run Redpanda Tuner (Crucial for performance)
      command: rpk redpanda tune all
      register: tune_result
      changed_when: "'Tuning parameters applied' in tune_result.stdout"
      failed_when: false

    - name: Start Redpanda Service
      systemd:
        name: redpanda
        state: started
        enabled: yes

    # Force a flush of handlers to ensure Redpanda is UP and ready for management
    - meta: flush_handlers

    # ====================================================================
    # Phase 2: SCRAM User Bootstrapping (Runs Once)
    # ====================================================================
    
    - name: Wait for Cluster API to be ready (must run once)
      command: rpk cluster health
      register: health_check
      until: health_check.rc == 0
      retries: 10
      delay: 5
      run_once: true

    - name: Create SCRAM Superuser (Runs only once on the first node)
      command: >
        rpk security user create {{ rp_superuser }}
        -p {{ rp_password }}
        --mechanism SCRAM-SHA-256
        --api-urls 127.0.0.1:9644
      register: create_user
      failed_when: 
        - create_user.rc != 0
        - "'User already exists' not in create_user.stderr" 
        - "'User already exists' not in create_user.stdout"
      run_once: true

  handlers:
    - name: Restart Redpanda
      systemd:
        name: redpanda
        state: restarted
        